Fixed
Signed-off-by: Sai Medhini Reddy Maryada <saimedhinireddymaryada@Sais-MacBook-Pro.local>

diff --git a/.github/workflows/update_file.yml b/.github/workflows/update_file.yml
--- a/.github/workflows/update_file.yml
+++ b/.github/workflows/update_file.yml
@@ -50,7 +50,7 @@ jobs:
       - name: printed
         run: |
           echo "Checking find pattern in CHANGELOG.md..."
-          grep -n "- Your contribution here." CHANGELOG.md || echo "Pattern not found."
+          grep -n "here" CHANGELOG.md || echo "Pattern not found."
       - name: Update CHANGELOG
         uses: jacobtomlinson/gha-find-replace@v3
         if: ${{ steps.cpr.outputs.pull-request-number != '' }}
