Fixed
Signed-off-by: Sai Medhini Reddy Maryada <saimedhinireddymaryada@Sais-MacBook-Pro.local>

diff --git a/.github/workflows/update_file.yml b/.github/workflows/update_file.yml
--- a/.github/workflows/update_file.yml
+++ b/.github/workflows/update_file.yml
@@ -47,12 +47,16 @@ jobs:
           base: main
           committer: opensearchpy-api-update-bot <noreply@github.com>
           author: opensearchpy-api-update-bot <noreply@github.com>
+      - name: printed
+        run: |
+          echo "Checking find pattern in CHANGELOG.md..."
+          grep -n "\\- Your contribution here." CHANGELOG.md || echo "Pattern not found."
       - name: Update CHANGELOG
         uses: jacobtomlinson/gha-find-replace@v3
         if: ${{ steps.cpr.outputs.pull-request-number != '' }}
         with:
           include: CHANGELOG.md
-          find: "\\* Your contribution here."
+          find: "\\- Your contribution here."
           replace: "- Updated opensearch-py to reflect the latest OpenSearch API spec ([#${{steps.cpr.outputs.pull-request-number}}](https://github.com/saimedhi/opensearch-py/pull/${{steps.cpr.outputs.pull-request-number}}))\n- Your contribution here."
       - name: Commit and Push
         if: ${{ steps.cpr.outputs.pull-request-number != '' }}
